AllCops:
  TargetRubyVersion: '3.2.2'
  NewCops: enable
require:
  - rubocop-rails

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Metrics/MethodLength:
  Max: 50
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 20
Naming/VariableNumber:
  Enabled: false
Layout/LineLength:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Style/HashSyntax:
  Enabled: false
